services:
  next:
    build: 
      context: .
      dockerfile: docker/next/Dockerfile
    environment:
      - APP_ENV=dev
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    volumes:
      - ".:/app"